stages:
  - zip_and_upload

default:
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest

variables:
  S3_BUCKET_NAME: "evgeny.lambda.functions"


.zip_and_upload: &zip_and_upload
  stage: zip_and_upload
  tags:
    -  gitlab ci
  before_script:
    # Authenticate with AWS
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws configure set default.region $AWS_REGION
  script:
    - cd $DIRECTORY_NAME
    - zip $FUNCTION_NAME.zip lambda_function.py
    - echo "file zipped"
    - aws s3 cp $FUNCTION_NAME.zip s3://$S3_BUCKET_NAME/
    - echo "zip uploaded"
    - aws lambda update-function-code --function-name $FUNCTION_NAME --s3-bucket $S3_BUCKET_NAME --s3-key $FUNCTION_NAME.zip
    - echo "lambda updated"

create_user_lambda_job:
  <<: *zip_and_upload
  variables:
    DIRECTORY_NAME: "create_user_lambda"
    FUNCTION_NAME: "gitlab_create_user"
  only:
    changes:
      - create_user_lambda/lambda_function.py

csv_to_excel_lambda_job:
  <<: *zip_and_upload
  variables:
    DIRECTORY_NAME: "csv_to_excel_lambda"
    FUNCTION_NAME: "lambda_csv_to_excel"
  only:
    changes:
      - csv_to_excel_lambda/lambda_function.py

discord_message_lambda_job:
  <<: *zip_and_upload
  variables:
    DIRECTORY_NAME: "discord_message_lambda"
    FUNCTION_NAME: "lambda_discord_msg"
  only:
    changes:
      - discord_message_lambda/lambda_function.py

new_project_lambda_job:
  <<: *zip_and_upload
  variables:
    DIRECTORY_NAME: "new_project_lambda"
    FUNCTION_NAME: "gitlab_new_project" 
  only:
    changes:
      - new_project_lambda/lambda_function.py

wiki_tops_lambda_job:
  <<: *zip_and_upload
  variables:
    DIRECTORY_NAME: "wiki_tops_lambda"
    FUNCTION_NAME: "wikipedia_func"
  only:
    changes:
      - wiki_tops_lambda/lambda_function.py

backup_lambda_job:
  <<: *zip_and_upload
  variables:
    DIRECTORY_NAME: "backup_lambda"
    FUNCTION_NAME: "lambda-Backup"
  only:
    changes:
      - backup_lambda/lambda_function.py