name: Workflow to Zip and Upload Lambda Functions to S3 and update them

on:
  push:
    branches:
      - 'master'
    paths:
      - 'gitlab_create_user/**'
      - 'csv_to_excel/**'
      - 'discord_message/**'
      - 'gitlab_new_project/**'
      - 'wiki_tops/**'
      - 'backup_lambdas/**'
      - '.github/workflows/lambdas_on_push_workflow.yaml'

jobs:
  test_changed_files:
    runs-on: ubuntu-latest
    outputs:
      file_list: ${{ steps.file_list.outputs.CHANGED_FILES }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List changed files
        id: file_list
        run: |
          changed_files=$(git diff-tree --no-commit-id --name-only -r ${{ github.sha }} |
                    grep -E -v '^(web_app/|\.github/)' |  # Exclude files matching 'web_app/**' and '.github/**'
                    grep '.py' || true)
          echo "$changed_files"
          echo "CHANGED_FILES=$changed_files" >> $GITHUB_OUTPUT
          echo ${{ env.CHANGED_FILES }}
          echo ${{ steps.file-list.outputs.CHANGED_FILES }}

      #- name: Install Python dependencies
      #  run: pip install -r requirements.txt

      - name: Run pytest on changed files
        run: |
          for file_path in ${{ steps.file-list.outputs.CHANGED_FILES }}; do
            folder_path=$(dirname $file_path)
            cd ${{ github.workspace }}/$folder_path
            # pytest test.py this line will be implement in the future when each function has it's own test file
          done

      - name: Set output for next job
        run: |
          echo "::set-output name=file_list::${{ env.CHANGED_FILES }}"
          echo "${{ env.CHANGED_FILES }}"

  zip_and_upload_template:
    runs-on: ubuntu-latest
    needs: test_changed_files
    env:
      LIST: ${{ needs.test_changed_files.outputs.file-list }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List changed files (inherited from test_changed_files)
        run: |
          echo "Changed files:"
          echo "${{ env.LIST }}"

      - name: Zip and upload Lambda function
        run: |
          for file_path in ${{ env.LIST }}; do
            folder_path=$(dirname $file_path)
            cd ${{ github.workspace }}/$folder_path
            echo "Deploying Lambda function in folder: $folder_path"
            pwd
            zip -r $folder_path.zip .
            ls -la
            aws s3 cp $folder_path.zip s3://${{ secrets.S3_BUCKET_NAME }}/
            function_name=$(basename $folder_path)
            aws lambda update-function-code --function-name $function_name --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --s3-key $folder_path.zip
          done
