name: Workflow to Zip and Upload Lambda Functions to S3 and update them

on:
  push:
    branches:
      - 'master'
    paths:
      - 'gitlab_create_user/**'
      - 'csv_to_excel/**'
      - 'discord_message/**'
      - 'gitlab_new_project/**'
      - 'wiki_tops/**'
      - 'backup_lambdas/**'
      - '.github/workflows/lambdas_on_push_workflow.yaml'

jobs:
  test_changed_files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: List and filter changed Python files
        run: |
          git fetch --prune --unshallow
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} |
                          grep -E -v '^(web_app/|\.github/)' |
                          grep '.py' || true)
          echo "$changed_files" > changed_files.env  # Write to environment file
          cat changed_files.env

      - name: Debug changed files
        run: |
          cat changed_files.env  # Check if the environment file is correctly populated

      #- name: Install Python dependencies
      #  run: pip install -r requirements.txt

      - name: Run pytest on changed files
        run: |
          for file_path in $(cat changed_files.env); do
            folder_path=$(dirname $file_path)
            cd ${{ github.workspace }}/$folder_path
            pwd
            # pytest test.py this line will be implement in the future when each function has it's own test file
          done

      - name: Upload changed files environment file
        uses: actions/upload-artifact@v2
        with:
          name: changed-files
          path: changed_files.env

  zip_and_upload_template:
    runs-on: ubuntu-latest
    needs: test_changed_files
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download changed files environment file
        uses: actions/download-artifact@v2
        with:
          name: changed-files

      - name: Read file list from environment file
        run: |
          cat changed_files.env

      - name: Zip and upload Lambda function
        run: |
          file_list=$(cat changed_files.env)
          for file_path in $file_list; do
            folder_path=$(dirname $file_path)
            echo "Deploying Lambda function in folder: $folder_path"
            cd ${{ github.workspace }}/$folder_path
            pwd
            function_name=$(basename $file_path)
            zip -r $function_name.zip .
            ls -la
            aws s3 cp $function_name.zip s3://${{ secrets.S3_BUCKET_NAME }}/
            aws lambda update-function-code --function-name $function_name --s3-bucket ${{ secrets.S3_BUCKET_NAME }} --s3-key $function_name.zip
          done
